name: Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint_and_prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install pnpm
        run: |
          npm install -g pnpm@9.0.6

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint and Prettier
        run: |
          pnpm run lint
          pnpm run format
